import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopMenu from "@/components/TopMenu/top-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "South Park App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/south-park.png" />
      </head>
      <body className={inter.className}>
        <TopMenu />
        {children}
      </body>
    </html>
  );
}